### PR TITLE
fix(cli): wire SQUAD_TEAM_ROOT into squad resolution for subprocess compatibility (#734)

### LINKED ISSUE #734: bug: squad nap fails when invoked via bang command (!) in Windows PowerShell terminal
## Problem

Running `squad nap` via Copilot CLI's bang command (`!squad nap` or `!npx @bradygaster/squad-cli nap`) in a Windows PowerShell terminal fails. The `!` prefix is used in Copilot CLI to execute shell commands directly from the chat interface.

## Environment

- **OS:** Windows 11
- **Terminal:** PowerShell 7.6
- **Shell:** Copilot CLI (`ghcs` / `gh copilot`)
- **Squad CLI:** 0.9.1

## Steps to Reproduce

1. Open a Copilot CLI session in Windows PowerShell
2. Run: `!npx @bradygaster/squad-cli nap`
3. Observe failure

## Expected Behavior

`squad nap` should execute the nap/archival cycle (decisions archive, history summarization, git commit) the same way it works when run directly in a PowerShell terminal outside of Copilot CLI.

## Likely Causes

- **PowerShell `!` history expansion conflict:** In PowerShell, `!` has special meaning for history recall (`!n` recalls command n). The bang prefix in Copilot CLI may conflict with PowerShell's history operator.
- **stdin/TTY issues:** `squad nap` may require interactive stdin that's not available when invoked as a subprocess from Copilot CLI's bang command handler.
- **Process spawning:** The bang command may spawn a child process differently than direct terminal execution — different env vars, working directory, or signal handling.

## Additional Context

- This was discovered during a Copilot CLI session working on bradygaster/squad (2026-04-01)
- The nap command works fine when run directly in PowerShell (not via bang)
- Other bang commands (`!git status`, `!gh issue list`) work normally in the same terminal
- The issue may be specific to commands that do interactive work (git commits, file I/O) rather than read-only commands

## Investigation Needed

- Capture the exact error output when running via bang
- Test if the issue is PowerShell-specific or affects cmd.exe too
- Test if `!npx @bradygaster/squad-cli nap --dry-run` works (read-only mode)
- Check if the nap command's git operations (`git add`, `git commit`) need a TTY

### PR DESCRIPTION
**Pull request by AmandaSilver**
### What
Wires the \--team-root\ / \SQUAD_TEAM_ROOT\ env var into the \
esolveSquad()\ calls for the \
ap\, \status\, and \cost\ commands. Previously the flag was parsed at CLI entry but never passed through to resolution.

### Why
\squad nap\ (and other commands) fail when invoked as a subprocess where \process.cwd()\ differs from the interactive shell — e.g. Copilot CLI bang commands (\!squad nap\) on Windows (#734). The \--team-root\ flag was already parsed and stored in \SQUAD_TEAM_ROOT\, but no command ever read it.

### How
- Added \getSquadStartDir()\ helper: returns \SQUAD_TEAM_ROOT ?? process.cwd()\
- Updated 3 \
esolveSquad(process.cwd())\ calls to use \
esolveSquad(getSquadStartDir())\
- Improved nap error message to show the searched directory and suggest \--team-root\

### Testing
- 5 new tests in \	est/cli/nap-subprocess.test.ts\ (all pass)
- 42 existing nap tests still pass
- No functional change when \SQUAD_TEAM_ROOT\ is unset (falls back to \process.cwd()\)

### Files Changed
- \packages/squad-cli/src/cli-entry.ts\ — \getSquadStartDir()\ + 3 call-site updates
- \	est/cli/nap-subprocess.test.ts\ — 5 new tests
- \.changeset/fix-nap-subprocess-cwd.md\ — patch changeset

### Exports
N/A — no new public API

### Breaking Changes
None — additive behavior only. Existing invocations are unchanged.

### Waivers
None

Closes #734

Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>

### CODE REVIEW

File: packages/squad-cli/src/cli-entry.ts [hunk 1]
```diff
@@ -106,6 +106,16 @@ const lazyRunShell = () => import('./cli/shell/index.js');
...
 const VERSION = getPackageVersion();
 
+/**
+ * Return the starting directory for squad resolution.
+ * Respects --team-root / SQUAD_TEAM_ROOT env var so that subprocesses
+ * (e.g. Copilot CLI bang commands) can locate .squad/ even when their
+ * working directory differs from the interactive shell. (#734)
+ */
+function getSquadStartDir(): string {
+  return process.env['SQUAD_TEAM_ROOT'] || process.cwd();
```
Comment (bradygaster) [inline packages/squad-cli/src/cli-entry.ts:116]: 👍

**Comment by diberry** [comment]
## ✅ APPROVE WITH FOLLOW-UP

This PR correctly fixes the subprocess invocation issue (#734) where \squad nap\ fails when \process.cwd()\ differs from the project root. The implementation is sound and safe.

### Code Review

**✅ Correctness**: \getSquadStartDir()\ properly implements the fallback pattern:
\\\	ypescript
return process.env['SQUAD_TEAM_ROOT'] || process.cwd();
\\\
Uses short-circuit OR for clean fallback to \process.cwd()\ when env var is unset.

**✅ Completeness**: All 3 \
esolveSquad()\ call sites are updated:
- \
ap\ command (line 659)
- \status\ command (line 571)
- \cost\ command (line 609)

Verified against the diff — no call sites missed.

**✅ Security**: No path traversal risk. The env var is:
1. Set by the CLI itself via the \--team-root\ flag parsing (controlled input)
2. Passed directly to \
esolveSquad()\ which already validates paths
3. Only used as a starting point for upward directory traversal (looking for \.squad/\)

**✅ Test Quality**: The Copilot bot's review comments were **valid when written** but are now **obsolete** — commit 01ed21a (current HEAD) addressed both concerns:
1. ✅ Test now uses \process.chdir(differentCwd)\ to simulate subprocess scenario
2. ✅ Test validates the actual behavior, not just runNap internals

The 5 tests cover:
- Subprocess with different cwd (the #734 fix scenario)
- Non-existent squadDir (error handling)
- Integration with actual nap logic (via \
unNap\)

Existing review threads are correctly marked as resolved/outdated.

**✅ Error Message Improvement**: The updated nap error is helpful:
\\\
No squad found (searched from \). Run "squad init" first, or use --team-root to specify the project directory.
\\\

### Required Actions Before Merge

1. **Rebase onto \dev\** — PR is behind base (mergeable_state: "behind")
2. **Squash 4 commits to 1** — commits should be:
   - \ix(cli): wire SQUAD_TEAM_ROOT into squad resolution for subprocess compatibility (#734)\
3. **Re-run CI** — Squad CI checks not visible on current commit; need verification after rebase

### Verdict
**APPROVE WITH FOLLOW-UP** — Code is production-ready. Merge blocked only by Git hygiene (rebase + squash), not code quality.

cc @AmandaSilver — please rebase onto latest \dev\ and squash to 1 commit, then CI should auto-run. Code review complete ✅

**Comment by diberry** [comment]
## Follow-up Issues Created

Two follow-up issues filed to extend this fix:

- **#835** — Extend \SQUAD_TEAM_ROOT\ to all \
esolveSquad()\ call sites (currently only nap/status/cost)
- **#836** — Add Copilot CLI subprocess integration tests for \SQUAD_TEAM_ROOT\ propagation

These capture the remaining work to make subprocess invocation robust across all commands.
